export default class VpaidPlayer {
    constructor(rmpVast: any);
    _rmpVast: any;
    _adContainer: any;
    _adPlayer: any;
    _params: any;
    _adParametersData: any;
    _debugRawConsoleLogs: any;
    _initialWidth: number;
    _initialHeight: number;
    _initialViewMode: string;
    _desiredBitrate: number;
    _vpaidCreativeUrl: string;
    _vpaidCreative: any;
    _vpaidScript: HTMLScriptElement;
    _vpaidIframe: HTMLIFrameElement;
    _vpaidAdLoaded: boolean;
    _initAdTimeout: NodeJS.Timeout;
    _vpaidCallbacks: {};
    _startAdTimeout: NodeJS.Timeout;
    _vpaidAdStarted: boolean;
    _vpaidVersion: number;
    _vpaid1AdDuration: number;
    _adStoppedTimeout: NodeJS.Timeout;
    _adSkippedTimeout: NodeJS.Timeout;
    _vpaidAdRemainingTimeInterval: NodeJS.Timeout;
    _vpaidRemainingTime: number;
    _vpaidCurrentVolume: number;
    _vpaidPaused: boolean;
    _vpaidLoadTimeout: NodeJS.Timeout;
    _vpaidAvailableInterval: NodeJS.Timeout;
    _vpaidSlot: HTMLDivElement;
    _onAdLoaded(): void;
    _onAdStarted(): void;
    _onAdStopped(): void;
    _onAdSkipped(): void;
    _onAdSkippableStateChange(): void;
    _onAdDurationChange(): void;
    _onAdVolumeChange(): void;
    _onAdImpression(): void;
    _onAdVideoStart(): void;
    _onAdVideoFirstQuartile(): void;
    _onAdVideoMidpoint(): void;
    _onAdVideoThirdQuartile(): void;
    _onAdVideoComplete(): void;
    _onAdClickThru(url: any, id: any, playerHandles: any): void;
    _onAdPaused(): void;
    _onAdPlaying(): void;
    _onAdLog(message: any): void;
    _onAdError(message: any): void;
    _onAdInteraction(): void;
    _onAdUserAcceptInvitation(): void;
    _onAdUserMinimize(): void;
    _onAdUserClose(): void;
    _onAdSizeChange(): void;
    _onAdLinearChange(): void;
    _onAdExpandedChange(): void;
    _onAdRemainingTimeChange(): void;
    _setCallbacksForCreative(): void;
    _unsetCallbacksForCreative(): void;
    _isValidVPAID(creative: any): boolean;
    _onVPAIDAvailable(): void;
    _onJSVPAIDLoaded(): void;
    _onJSVPAIDError(): void;
    getAdWidth(): any;
    getAdHeight(): any;
    getAdDuration(): any;
    getAdRemainingTime(): number;
    getCreativeUrl(): string;
    getAdVolume(): any;
    getAdPaused(): boolean;
    getAdExpanded(): any;
    getAdSkippableState(): any;
    getAdCompanions(): any;
    resizeAd(width: any, height: any, viewMode: any): void;
    stopAd(): void;
    pauseAd(): void;
    resumeAd(): void;
    expandAd(): void;
    collapseAd(): void;
    skipAd(): void;
    setAdVolume(volume: any): void;
    init(creativeUrl: any, vpaidSettings: any): void;
    destroy(): void;
}
//# sourceMappingURL=vpaid-player.d.ts.map