export function createAd(adAttributes?: {}): {
    id: any;
    sequence: any;
    adType: any;
    adServingId: any;
    categories: any[];
    expires: any;
    viewableImpression: {};
    system: any;
    title: any;
    description: any;
    advertiser: any;
    pricing: any;
    survey: any;
    errorURLTemplates: any[];
    impressionURLTemplates: any[];
    creatives: any[];
    extensions: any[];
    adVerifications: any[];
    blockedAdCategories: any[];
    followAdditionalWrappers: boolean;
    allowMultipleAds: boolean;
    fallbackOnNoAd: any;
};
